baseurl = "https://vrutkovs.eu/"
title = "Vadim Rutkovsky"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[pagination]
pagerSize = 20


[params]
author = "Vadim Rutkovsky"
info = "Senior rubber duck collector"
description = "Vadim Rutkovsky's personal site"
keywords = "blog,developer,personal"
avatarUrl = "images/avatar.png"

favicon = "/favicon.ico"
appleTouchIcon = "/apple-touch-icon.png"

hideCredits = true
hideCopyright = true

rtl = false

math = false

customCSS = ["css/extra-style.css"]
customJS = ["js/lightbox.js", "js/purify.min.js"]

hideColorSchemeToggle = true

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/vrutkovs/"
[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
weight = 4
url = "mailto:vadim@vrutkovs.eu"
[[params.social]]
name = "ActivityPub"
icon = "fa-brands fa-mastodon fa-2x"
weight = 4
url = "https://m.vrutkovs.eu/@vadim"
rel = "me"

# Menu links
[[menu.main]]
name = "Slides"
weight = 1
url = "/slides/"

[[menu.main]]
name = "Posts"
weight = 2
url = "/posts/"

[[menu.main]]
name = "What I'm Reading"
weight = 3
url = "/reading-list/"

[module]
[[module.imports]]
path = "hugo-coder"
[[module.imports]]
path = "hugo-notice"

[outputs]
home = ["html", "rss"]
page = ["html"]
